### PR TITLE
ecommerce-store

### PR DESCRIPTION
**Pull request by Adeboye-Adebisi2**
**In this PR, I made use of:**
- Html
- Stylesheet
- JavaScript and
- Images

### CODE REVIEW

**Comment by ferdinandchisom** [comment]
wow @Adeboye-Adebisi2 you're amazing you did so oo well

**Review by ferdinandchisom — APPROVED** [review]
wow awesome job @Adeboye-Adebisi2 you can now proceed in creating your various links
congratulations

**Comment by Adeboye-Adebisi2** [comment]
Merging for  production

**Comment by Adeboye-Adebisi2** [comment]
Merging

**Pull request merged**
